### ISSUE TITLE
Sample App: Multiple issues

### ISSUE THREAD

**Issue by Jaycyn** [mongodb-university/stitch-tutorial-todo-ios#3]
The tutorial app will simply not compile. There are a number of issues.

1) Sandboxing issue: 

> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

2) Severely outdated and depreciated code

3) Path's are incorrect. As close as I can tell the project is looking for Target Support Files in /ToDo/Pods/Pods where it should be /ToDo/Pods I believe

> /Users/xxxx/Desktop/stitch-tutorial-todo-ios-master/Todo/Todo.xcodeproj The file “Pods-Todo.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/xxxx/Desktop/stitch-tutorial-todo-ios-master/Todo/Pods/Pods/Target Support Files/Pods-Todo/Pods-Todo.debug.xcconfig)

The Podfile was updated and is correct and the Constants.swift file was updated to point to my Atlas.

<img width="408" alt="Stitch Errors" src="https://user-images.githubusercontent.com/19558530/59161377-05575f00-8ab0-11e9-926f-848f320aaada.png">

<img width="405" alt="Stitch File Path" src="https://user-images.githubusercontent.com/19558530/59161453-c1b12500-8ab0-11e9-850b-28d70b10cc64.png">

**Comment by Jaycyn** [comment]
Update: The Stitch sample app now builds and runs.

There are a number of depreciated functions but those can be ignored for the time being.

You must use Cocoapods command line app 1.6.1 or higher. If you are unsure, just update it with

[sudo] gem install cocoapods

then navigate (in terminal) to the stitch-tutorial-todo-ios-master folder and into the Todo folder

and run

pod install --repo-update

The current Mac app for Cocoapods (1.5.2) does not appear to work correctly so install the pods from the command line only.

**Comment by terakilobyte** [comment]
Thanks for raising this to our attention. We've updated the readme to state the cocoapods version requirement.
